services:
  - type: web
    name: nyamatrack-api
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn nyamatrack.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4