# Generated by Django 5.0.2 on 2026-03-09 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_spoiled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StockRemoval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_removed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('spoiled', 'Spoiled'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('other', 'Other')], default='spoiled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('removal_date', models.DateTimeField(auto_now_add=True)),
                ('original_receive_date', models.DateTimeField()),
                ('days_at_removal', models.IntegerField()),
                ('meat_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_records', to='inventory.meatcut')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removals', to='inventory.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_removals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stock Removals',
                'ordering': ['-removal_date'],
            },
        ),
    ]
