# Generated by Django 5.0.2 on 2026-03-18 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_is_spoiled_stockremoval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['receive_date'], 'verbose_name_plural': 'Stock'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_spoiled',
        ),
        migrations.CreateModel(
            name='RemovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.IntegerField(help_text='Original stock entry ID')),
                ('weight_removed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('spoilage', 'Spoilage'), ('expired', 'Expired'), ('damaged', 'Damaged'), ('quality_issue', 'Quality Issue'), ('other', 'Other')], default='spoilage', max_length=20)),
                ('custom_reason', models.TextField(blank=True, help_text='Additional details if reason is "other"')),
                ('days_old_at_removal', models.IntegerField()),
                ('receive_date', models.DateTimeField(help_text='Original receive date of the stock')),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('meat_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_history', to='inventory.meatcut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Removal History',
                'ordering': ['-removed_at'],
            },
        ),
        migrations.DeleteModel(
            name='StockRemoval',
        ),
    ]
